name: Packer-AMI-Build

on:
  push:
    branches:
      - main
      - staging
      - demo

jobs:
  packer-ami-build:
    runs-on: ubuntu-latest
    environment: 
      name: AWS_DEPLOYMENT
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Configure Git safe directory
        run: git config --global --add safe.directory /__w/webapp/webapp

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.5'

      # Integration Test
      - name: Create config.yaml file
        run: |
          touch config.yaml
          echo database: >> config.yaml
          echo "  test_host: localhost" >> config.yaml
          echo "  test_port: 5432" >> config.yaml
          echo "  test_username: postgres" >> config.yaml
          echo "  test_password: postgres" >> config.yaml
          echo "  test_name: webapp-test-${{ github.sha }}" >> config.yaml
      
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost; do
            echo "Waiting for postgres to be ready..."
            sleep 1
          done

      - name: Create database
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -c "CREATE DATABASE \"webapp-test-${{ github.sha }}\";" -v ON_ERROR_STOP=1

      - name: Install dependencies
        run: go mod tidy

      - name: Test
        run: go test -v ./...


      # Build Project
      - name: Build project
        run: go build -o app ./cmd/api/main.go


      # Build AMI
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest

      - name: Init Packer
        run: packer init ./packer

      - name: Install AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Build AMI
        run: packer build ./packer | tee packer_output.log

      - name: Extract AMI ID
        id: get_ami_id
        run: |
          AMI_ID=$(grep 'artifact,0,id' packer_output.log | cut -d, -f6 | cut -d: -f2)
          echo "AMI ID is $AMI_ID"
          echo $AMI_ID > AMI_ID.txt
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ami-id
          path: ami_id.txt